/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lefty

import lefty.dagger.DaggerApplicationComponent
import lefty.pipeline.Specification
import lefty.pipeline.Step
import lefty.pipeline.dagger.PipelineComponent
import lefty.pipeline.dagger.PipelineModule
import java.nio.file.Paths
import javax.inject.Inject
import javax.inject.Provider

class App @Inject constructor(
        private val pipelineBuilder: Provider<PipelineComponent.Builder>
) {
    fun run() {
        val pipeline = pipelineBuilder
                .get()
                .pipelineModule(
                        PipelineModule(
                                Paths.get("./test"),
                                Specification(
                                        listOf(
                                                Step(
                                                        "the image",
                                                        listOf(
                                                                "command 1",
                                                                "command 2"
                                                        )
                                                )
                                        )
                                )
                        )
                )
                .build()
                .pipeline()
        pipeline.run()
    }
}

fun main(args: Array<String>) {
    val applicationComponent = DaggerApplicationComponent
            .builder()
            .build()

    val app = applicationComponent.app()
    app.run()
}
